# Generated by Django 6.1.1 on 2026-09-21 18:10

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('kind', models.CharField(choices=[('reception', 'Reception'), ('pharmacy', 'Pharmacy'), ('manager', 'Manager'), ('custom', 'Custom')], db_index=True, default='custom', max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('allow_negative', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expense_date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payee', models.CharField(blank=True, max_length=150)),
                ('purpose', models.TextField()),
                ('receipt_number', models.CharField(blank=True, max_length=80)),
                ('attachment', models.FileField(blank=True, upload_to='expenses/%Y/%m/')),
                ('is_void', models.BooleanField(db_index=True, default=False)),
                ('void_reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses_created', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.expensecategory')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.wallet')),
            ],
            options={
                'ordering': ('-expense_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Turnover',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('handed_over_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnovers_handed_over', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='turnovers_received', to=settings.AUTH_USER_MODEL)),
                ('destination_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnovers_received', to='finance.wallet')),
                ('source_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnovers_sent', to='finance.wallet')),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(('period_end__gt', models.F('period_start'))), name='turnover_period_valid'), models.CheckConstraint(condition=models.Q(('source_wallet', models.F('destination_wallet')), _negated=True), name='turnover_wallets_differ')],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=16)),
                ('transaction_date', models.DateTimeField(db_index=True)),
                ('category', models.CharField(db_index=True, max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=120, unique=True)),
                ('source_type', models.CharField(blank=True, db_index=True, max_length=50)),
                ('source_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_entries', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.wallet')),
            ],
            options={
                'ordering': ('-transaction_date', '-created_at'),
                'indexes': [models.Index(fields=['source_type', 'source_id'], name='finance_wal_source__39612f_idx')],
            },
        ),
    ]
