# Generated by Django 6.1.1 on 2026-09-23 01:52

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


def populate_finance_lifecycle_metadata(apps, schema_editor):
    Expense = apps.get_model('finance', 'Expense')
    Turnover = apps.get_model('finance', 'Turnover')
    WalletTransaction = apps.get_model('finance', 'WalletTransaction')

    for expense in Expense.objects.filter(is_void=True):
        expense.voided_by_id = expense.created_by_id
        expense.voided_at = expense.updated_at
        if not expense.void_reason:
            expense.void_reason = 'Voided before finance lifecycle auditing was introduced.'
        expense.save(update_fields=('voided_by', 'voided_at', 'void_reason'))

    for turnover in Turnover.objects.filter(received_by__isnull=False):
        turnover.status = 'received'
        turnover.received_at = turnover.created_at
        turnover.save(update_fields=('status', 'received_at'))

    original_references = {
        'purchase_reversal': lambda reference: reference.removesuffix(':void-payment') + ':payment',
        'sale_reversal': lambda reference: reference.removesuffix(':void-payment') + ':payment',
        'supplier_payment_reversal': lambda reference: reference.removesuffix(':void'),
        'expense_reversal': lambda reference: reference.removesuffix(':void'),
    }
    for reversal in WalletTransaction.objects.filter(category__in=original_references):
        original_reference = original_references[reversal.category](reversal.reference)
        original = WalletTransaction.objects.filter(reference=original_reference).first()
        if original:
            reversal.reverses_id = original.pk
            reversal.save(update_fields=('reverses',))


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses_voided', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='turnover',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turnover',
            name='status',
            field=models.CharField(choices=[('handed_over', 'Handed over'), ('received', 'Received')], db_index=True, default='handed_over', max_length=20),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='reverses',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_entry', to='finance.wallettransaction'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='category',
            field=models.CharField(choices=[('reception_income', 'Reception income'), ('reception_refund', 'Reception refund'), ('pharmacy_purchase', 'Pharmacy purchase'), ('pharmacy_sale', 'Pharmacy sale'), ('supplier_payment', 'Supplier payment'), ('purchase_reversal', 'Purchase reversal'), ('sale_reversal', 'Sale reversal'), ('supplier_payment_reversal', 'Supplier payment reversal'), ('expense', 'Expense'), ('expense_reversal', 'Expense reversal'), ('turnover', 'Turnover')], db_index=True, max_length=50),
        ),
        migrations.RunPython(populate_finance_lifecycle_metadata, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='expense_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_void', False), ('void_reason', ''), ('voided_at__isnull', True), ('voided_by__isnull', True)), models.Q(('is_void', True), ('voided_at__isnull', False), ('voided_by__isnull', False), models.Q(('void_reason', ''), _negated=True)), _connector='OR'), name='expense_void_metadata_consistent'),
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_expense_category_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='turnover',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='turnover_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='turnover',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('received_at__isnull', True), ('received_by__isnull', True), ('status', 'handed_over')), models.Q(('received_at__isnull', False), ('received_by__isnull', False), ('status', 'received')), _connector='OR'), name='turnover_receipt_metadata_consistent'),
        ),
        migrations.AddConstraint(
            model_name='turnover',
            constraint=models.UniqueConstraint(fields=('source_wallet', 'period_start', 'period_end'), name='unique_turnover_source_period'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='unique_wallet_code_ci'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_wallet_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'custom'), _negated=True), fields=('kind',), name='unique_system_wallet_kind'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('allow_negative', True), ('balance__gte', 0), _connector='OR'), name='wallet_balance_respects_negative_policy'),
        ),
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='wallet_transaction_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_id', ''), ('source_type', '')), models.Q(models.Q(('source_type', ''), _negated=True), models.Q(('source_id', ''), _negated=True)), _connector='OR'), name='wallet_transaction_source_pair'),
        ),
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.CheckConstraint(condition=models.Q(('id', models.F('reverses_id')), _negated=True), name='wallet_transaction_not_self_reversal'),
        ),
    ]
