# Generated by Django 6.1.1 on 2026-09-22 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_laboratory_history(apps, schema_editor):
    LabOrder = apps.get_model('laboratory', 'LabOrder')
    LabOrderItem = apps.get_model('laboratory', 'LabOrderItem')

    for item in LabOrderItem.objects.select_related('test').iterator():
        item.test_code = item.test.code
        item.test_name = item.test.name
        item.specimen_type = item.test.specimen_type
        update_fields = ['test_code', 'test_name', 'specimen_type']
        if item.result and (not item.resulted_by_id or not item.resulted_at):
            item.result = ''
            item.is_abnormal = False
            item.resulted_by_id = None
            item.resulted_at = None
            update_fields.extend(['result', 'is_abnormal', 'resulted_by', 'resulted_at'])
        elif not item.result:
            item.is_abnormal = False
            item.resulted_by_id = None
            item.resulted_at = None
            update_fields.extend(['is_abnormal', 'resulted_by', 'resulted_at'])
        item.save(update_fields=update_fields)

    for order in LabOrder.objects.iterator():
        update_fields = []
        if order.status == 'cancelled':
            order.cancelled_at = order.updated_at
            update_fields.append('cancelled_at')
            if not order.cancelled_by_id or not order.cancellation_reason:
                # Preserve the record while making legacy cancellation metadata explicit.
                order.cancelled_by_id = order.cancelled_by_id or order.ordered_by_id
                order.cancellation_reason = order.cancellation_reason or 'Legacy cancellation'
                update_fields.extend(['cancelled_by', 'cancellation_reason'])
        if order.status in ('collected', 'in_progress', 'completed'):
            first_result = order.items.filter(resulted_at__isnull=False).order_by('resulted_at').first()
            order.collected_by_id = first_result.resulted_by_id if first_result else order.ordered_by_id
            order.collected_at = first_result.resulted_at if first_result else order.ordered_at
            update_fields.extend(['collected_by', 'collected_at'])
        if update_fields:
            order.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_laborder_cancellation_reason_laborder_cancelled_by'),
        ('patients', '0004_patientnote_archival'),
        ('reception', '0004_visit_visit_discount_approval_consistent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='laborder',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laborder',
            name='collected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laborder',
            name='collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders_collected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laborderitem',
            name='specimen_type',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='laborderitem',
            name='test_code',
            field=models.CharField(blank=True, editable=False, max_length=30),
        ),
        migrations.AddField(
            model_name='laborderitem',
            name='test_name',
            field=models.CharField(blank=True, editable=False, max_length=150),
        ),
        migrations.RunPython(backfill_laboratory_history, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='laborder',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cancelled_at__isnull', False), ('cancelled_by__isnull', False), ('status', 'cancelled'), models.Q(('cancellation_reason', ''), _negated=True)), models.Q(models.Q(('status', 'cancelled'), _negated=True), ('cancelled_by__isnull', True), ('cancelled_at__isnull', True), ('cancellation_reason', '')), _connector='OR'), name='lab_order_cancellation_consistent'),
        ),
        migrations.AddConstraint(
            model_name='laborder',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('collected_at__isnull', False), ('collected_by__isnull', False), ('status__in', ('collected', 'in_progress', 'completed'))), models.Q(('status__in', ('ordered', 'cancelled')), ('collected_at__isnull', True), ('collected_by__isnull', True)), models.Q(('collected_at__isnull', False), ('collected_by__isnull', False), ('status', 'cancelled')), _connector='OR'), name='lab_order_collection_consistent'),
        ),
        migrations.AddConstraint(
            model_name='laborderitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('result', ''), _negated=True), ('resulted_at__isnull', False), ('resulted_by__isnull', False)), models.Q(('result', ''), ('is_abnormal', False), ('resulted_at__isnull', True), ('resulted_by__isnull', True)), _connector='OR'), name='lab_result_metadata_consistent'),
        ),
    ]
