# Generated by Django 6.1.1 on 2026-09-21 18:47

import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('patients', '0001_initial'),
        ('pharmacy', '0002_purchase_void_reason_purchase_voided_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='prescription_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddIndex(
            model_name='medicinebatch',
            index=models.Index(fields=['medicine', 'is_active', 'expiry_date'], name='pharmacy_me_medicin_777e26_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['supplier', 'is_void', 'payment_date'], name='pharmacy_su_supplie_ce8a50_idx'),
        ),
        migrations.AddConstraint(
            model_name='medicinebatch',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_received__gte', 0)), name='batch_received_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='medicinebatch',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_available__gte', 0)), name='batch_available_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='purchase_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount__gte', 0)), name='purchase_paid_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'posted'), ('void_reason', ''), ('voided_by__isnull', True)), models.Q(('status', 'void'), ('voided_by__isnull', False), models.Q(('void_reason', ''), _negated=True)), _connector='OR'), name='purchase_void_metadata_consistent'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='sale_subtotal_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='sale_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount__gte', 0)), name='sale_paid_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount', django.db.models.expressions.CombinedExpression(models.F('subtotal'), '-', models.F('discount_amount')))), name='sale_total_equation'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount', 0), models.Q(('discount_reason', ''), _negated=True), _connector='OR'), name='sale_discount_reason_required'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'posted'), ('void_reason', ''), ('voided_by__isnull', True)), models.Q(('status', 'void'), ('voided_by__isnull', False), models.Q(('void_reason', ''), _negated=True)), _connector='OR'), name='sale_void_metadata_consistent'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_after__gte', 0)), name='stock_movement_after_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_change', 0), _negated=True), name='stock_movement_change_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='supplierpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='supplier_payment_positive'),
        ),
        migrations.AddConstraint(
            model_name='supplierpayment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_void', False), ('void_reason', ''), ('voided_by__isnull', True)), models.Q(('is_void', True), ('voided_by__isnull', False), models.Q(('void_reason', ''), _negated=True)), _connector='OR'), name='supplier_payment_void_metadata_consistent'),
        ),
    ]
