# Generated by Django 6.1.1 on 2026-09-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_sale_prescription_reference_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='medicinebatch',
            constraint=models.CheckConstraint(condition=models.Q(('sale_price__gte', models.F('purchase_price'))), name='batch_sale_not_below_cost'),
        ),
    ]
