# Generated by Django 6.1.1 on 2026-09-22 02:21

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import hr.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def mark_existing_paid_payroll(apps, schema_editor):
    PayrollRecord = apps.get_model('hr', 'PayrollRecord')
    PayrollRecord.objects.filter(paid_at__isnull=False).update(status='paid')


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_service_is_discountable'),
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ('-start_date',),
            },
            bases=(hr.models.ValidatedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EmploymentDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('contract', 'Contract'), ('identity', 'Identity'), ('certificate', 'Certificate'), ('license', 'Professional license'), ('other', 'Other')], max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='hr/employee-documents/%Y/%m/')),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(hr.models.ValidatedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateField(db_index=True)),
                ('is_paid', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('date',),
            },
            bases=(hr.models.ValidatedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leave_type', models.CharField(choices=[('annual', 'Annual'), ('sick', 'Sick'), ('unpaid', 'Unpaid'), ('maternity', 'Maternity'), ('paternity', 'Paternity'), ('other', 'Other')], max_length=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=12)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-start_date',),
            },
            bases=(hr.models.ValidatedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PayrollComponent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('allowance', 'Allowance'), ('bonus', 'Bonus'), ('overtime', 'Overtime'), ('tax', 'Tax'), ('advance', 'Advance repayment'), ('deduction', 'Other deduction')], max_length=12)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
            ],
            options={
                'ordering': ('kind', 'description'),
            },
            bases=(hr.models.ValidatedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SalaryHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('effective_from', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ('-effective_from',),
            },
            bases=(hr.models.ValidatedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-start_date',),
            },
            bases=(hr.models.ValidatedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_minutes', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ('name',),
            },
            bases=(hr.models.ValidatedModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_date',
            field=models.DateField(blank=True, help_text='Set for overnight shifts; defaults to attendance date.', null=True),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=12),
        ),
        migrations.RunPython(mark_existing_paid_payroll, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'terminated'), _negated=True), ('end_date__isnull', False), _connector='OR'), name='terminated_employee_has_end_date'),
        ),
        migrations.AddConstraint(
            model_name='payrollrecord',
            constraint=models.CheckConstraint(condition=models.Q(('deductions__lte', django.db.models.expressions.CombinedExpression(models.F('base_salary'), '+', models.F('allowances')))), name='payroll_deductions_not_above_gross'),
        ),
        migrations.AddField(
            model_name='employmentassignment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_assignments', to='departments.department'),
        ),
        migrations.AddField(
            model_name='employmentassignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_history', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='employmentdocument',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='departments.department'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_leave_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollcomponent',
            name='payroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='hr.payrollrecord'),
        ),
        migrations.AddField(
            model_name='salaryhistory',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_history', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_assignments', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='hr.workshift'),
        ),
        migrations.AddConstraint(
            model_name='holiday',
            constraint=models.UniqueConstraint(fields=('date', 'department'), name='unique_holiday_date_department'),
        ),
        migrations.AddConstraint(
            model_name='salaryhistory',
            constraint=models.UniqueConstraint(fields=('employee', 'effective_from'), name='unique_salary_effective_date'),
        ),
    ]
