# Generated by Django 6.1.1 on 2026-09-22 06:18

import hr.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_employmentassignment_employmentdocument_holiday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshift',
            name='working_days',
            field=models.JSONField(default=hr.models.default_working_days, help_text='ISO-style weekday numbers: Monday=0 through Sunday=6.'),
        ),
    ]
