# Generated by Django 6.1.1 on 2026-09-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('administrator', 'System administrator'), ('reception', 'Reception'), ('pharmacy', 'Pharmacy'), ('laboratory', 'Laboratory'), ('finance', 'Finance'), ('manager', 'Manager'), ('hr', 'Human resources'), ('clinician', 'Clinician')], db_index=True, default='reception', max_length=20),
        ),
    ]
