# Generated by Django 6.1.1 on 2026-09-21 18:10

import django.core.validators
import django.db.models.deletion
import reception.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visit_number', models.CharField(default=reception.models.visit_number, editable=False, max_length=20, unique=True)),
                ('visit_date', models.DateTimeField(db_index=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_reason', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='registered', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visits_cancelled', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='departments.department')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='patients.patient')),
            ],
            options={
                'ordering': ('-visit_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='VisitService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visit_lines', to='departments.service')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_lines', to='reception.visit')),
            ],
        ),
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='visit_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='visit_discount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount__gte', 0)), name='visit_paid_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__lte', models.F('total_amount'))), name='visit_discount_not_above_total'),
        ),
        migrations.AddConstraint(
            model_name='visitservice',
            constraint=models.UniqueConstraint(fields=('visit', 'service'), name='unique_service_per_visit'),
        ),
    ]
