# Generated by Django 6.1.1 on 2026-09-21 18:22

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def backfill_visit_history(apps, schema_editor):
    Visit = apps.get_model('reception', 'Visit')
    VisitService = apps.get_model('reception', 'VisitService')
    for line in VisitService.objects.select_related('service').iterator():
        line.service_code = line.service.code
        line.service_name = line.service.name
        line.save(update_fields=('service_code', 'service_name'))
    for visit in Visit.objects.all().iterator():
        fields = []
        if visit.status == 'cancelled' and not visit.cancelled_at:
            visit.cancelled_at = visit.updated_at
            fields.append('cancelled_at')
        if visit.status == 'in_progress' and not visit.started_at:
            visit.started_at = visit.updated_at
            fields.append('started_at')
        if visit.status == 'completed' and not visit.completed_at:
            visit.completed_at = visit.updated_at
            fields.append('completed_at')
        if fields:
            visit.save(update_fields=fields)


def backfill_visit_payments(apps, schema_editor):
    Visit = apps.get_model('reception', 'Visit')
    VisitPayment = apps.get_model('reception', 'VisitPayment')
    WalletTransaction = apps.get_model('finance', 'WalletTransaction')
    for visit in Visit.objects.exclude(paid_amount=0).iterator():
        income = WalletTransaction.objects.filter(reference=f'visit:{visit.pk}:payment').first()
        VisitPayment.objects.create(
            visit_id=visit.pk, payment_type='payment', amount=visit.paid_amount, method='cash',
            notes='Migrated opening payment', received_by_id=visit.created_by_id,
            paid_at=visit.visit_date, wallet_transaction_id=income.pk if income else None,
        )
        if visit.status == 'cancelled':
            refund_entry = WalletTransaction.objects.filter(reference=f'visit:{visit.pk}:cancel').first()
            VisitPayment.objects.create(
                visit_id=visit.pk, payment_type='refund', amount=visit.paid_amount, method='cash',
                notes=visit.cancellation_reason or 'Migrated cancellation refund',
                received_by_id=visit.cancelled_by_id or visit.created_by_id,
                paid_at=visit.cancelled_at or visit.updated_at,
                wallet_transaction_id=refund_entry.pk if refund_entry else None,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('finance', '0001_initial'),
        ('patients', '0001_initial'),
        ('reception', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund')], default='payment', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank transfer'), ('mobile_money', 'Mobile money'), ('other', 'Other')], default='cash', max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('paid_at', 'created_at'),
            },
        ),
        migrations.AddField(
            model_name='visit',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visit',
            name='referral_source',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='visit',
            name='room',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='visit',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='visit_type',
            field=models.CharField(choices=[('outpatient', 'Outpatient'), ('emergency', 'Emergency'), ('follow_up', 'Follow-up'), ('inpatient', 'Inpatient')], db_index=True, default='outpatient', max_length=20),
        ),
        migrations.AddField(
            model_name='visitservice',
            name='service_code',
            field=models.CharField(blank=True, default='', editable=False, max_length=30),
        ),
        migrations.AddField(
            model_name='visitservice',
            name='service_name',
            field=models.CharField(blank=True, default='', editable=False, max_length=150),
        ),
        migrations.RunPython(backfill_visit_history, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount__lte', django.db.models.expressions.CombinedExpression(models.F('total_amount'), '-', models.F('discount_amount')))), name='visit_paid_not_above_net'),
        ),
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount', 0), models.Q(('discount_reason', ''), _negated=True), _connector='OR'), name='visit_discount_reason_required'),
        ),
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cancelled_by__isnull', False), ('status', 'cancelled'), models.Q(('cancellation_reason', ''), _negated=True), ('cancelled_at__isnull', False)), models.Q(models.Q(('status', 'cancelled'), _negated=True), ('cancelled_by__isnull', True), ('cancellation_reason', ''), ('cancelled_at__isnull', True)), _connector='OR'), name='visit_cancellation_metadata_consistent'),
        ),
        migrations.AddConstraint(
            model_name='visitservice',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='visit_service_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='visitservice',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='visit_service_price_nonnegative'),
        ),
        migrations.AddField(
            model_name='visitpayment',
            name='received_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visit_payments_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitpayment',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='reception.visit'),
        ),
        migrations.AddField(
            model_name='visitpayment',
            name='wallet_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visit_payment', to='finance.wallettransaction'),
        ),
        migrations.RunPython(backfill_visit_payments, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='visitpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='visit_payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='visitpayment',
            constraint=models.UniqueConstraint(condition=models.Q(('transaction_reference', ''), _negated=True), fields=('visit', 'transaction_reference'), name='unique_visit_payment_reference'),
        ),
    ]
