# Generated by Django 6.1.1 on 2026-09-21 18:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def backfill_standard_fees(apps, schema_editor):
    VisitService = apps.get_model('reception', 'VisitService')
    for line in VisitService.objects.select_related('service').iterator():
        line.standard_fee = line.service.standard_fee
        if line.unit_price != line.standard_fee and not line.price_override_reason:
            line.price_override_reason = 'Historical price imported during migration'
            line.price_overridden_by_id = line.visit.created_by_id
        line.save(update_fields=('standard_fee', 'price_override_reason', 'price_overridden_by'))


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_service_is_discountable'),
        ('reception', '0002_visitpayment_visit_cancelled_at_visit_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='discount_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='discount_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reception_discounts_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitservice',
            name='price_overridden_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reception_prices_overridden', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitservice',
            name='price_override_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='visitservice',
            name='standard_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12),
        ),
        migrations.RunPython(backfill_standard_fees, migrations.RunPython.noop),
        migrations.CreateModel(
            name='VisitQueueEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('queue_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('token_number', models.PositiveIntegerField()),
                ('priority', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('called', 'Called'), ('serving', 'Serving'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], db_index=True, default='waiting', max_length=12)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('serving_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visit_queue', to='departments.department')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entry', to='reception.visit')),
            ],
            options={
                'ordering': ('-priority', 'token_number'),
                'constraints': [models.UniqueConstraint(fields=('department', 'queue_date', 'token_number'), name='unique_daily_department_token'), models.CheckConstraint(condition=models.Q(('token_number__gt', 0)), name='queue_token_positive')],
            },
        ),
    ]
