# Generated by Django 6.1.1 on 2026-09-21 18:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_service_is_discountable'),
        ('patients', '0001_initial'),
        ('reception', '0003_visit_discount_approved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('discount_approved_by__isnull', True), ('discount_approved_at__isnull', True)), models.Q(('discount_approved_by__isnull', False), ('discount_approved_at__isnull', False)), _connector='OR'), name='visit_discount_approval_consistent'),
        ),
        migrations.AddConstraint(
            model_name='visitservice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('price_overridden_by__isnull', True), ('price_override_reason', ''), ('unit_price', models.F('standard_fee'))), models.Q(models.Q(('unit_price', models.F('standard_fee')), _negated=True), ('price_overridden_by__isnull', False), models.Q(('price_override_reason', ''), _negated=True)), _connector='OR'), name='visit_service_override_consistent'),
        ),
    ]
