# Generated by Django 6.1.1 on 2026-09-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_discountable',
            field=models.BooleanField(default=True),
        ),
    ]
