# Generated by Django 6.1.1 on 2026-09-22 12:14

import django.db.models.functions.text
from django.db import migrations, models


def normalize_catalog(apps, schema_editor):
    Department = apps.get_model('departments', 'Department')
    Service = apps.get_model('departments', 'Service')

    departments = list(Department.objects.all())
    services = list(Service.objects.all())

    department_codes = {}
    department_names = {}
    for department in departments:
        normalized_code = (department.code or '').strip().upper()
        normalized_name = (department.name or '').strip()
        if not normalized_code or not normalized_name:
            raise RuntimeError(f'Department {department.pk} has a blank code or name after normalization.')
        if normalized_code.casefold() in department_codes:
            raise RuntimeError(
                f'Departments {department_codes[normalized_code.casefold()]} and {department.pk} '
                'have colliding codes after normalization.'
            )
        if normalized_name.casefold() in department_names:
            raise RuntimeError(
                f'Departments {department_names[normalized_name.casefold()]} and {department.pk} '
                'have colliding names after normalization.'
            )
        department_codes[normalized_code.casefold()] = department.pk
        department_names[normalized_name.casefold()] = department.pk
        department.code = normalized_code
        department.name = normalized_name
        department.description = (department.description or '').strip()

    service_codes = {}
    service_names = {}
    for service in services:
        normalized_code = (service.code or '').strip().upper()
        normalized_name = (service.name or '').strip()
        name_key = (service.department_id, normalized_name.casefold())
        if not normalized_code or not normalized_name:
            raise RuntimeError(f'Service {service.pk} has a blank code or name after normalization.')
        if normalized_code.casefold() in service_codes:
            raise RuntimeError(
                f'Services {service_codes[normalized_code.casefold()]} and {service.pk} '
                'have colliding codes after normalization.'
            )
        if name_key in service_names:
            raise RuntimeError(
                f'Services {service_names[name_key]} and {service.pk} have colliding names in the same department.'
            )
        if service.standard_fee < 0:
            raise RuntimeError(f'Service {service.pk} has a negative standard fee.')
        service_codes[normalized_code.casefold()] = service.pk
        service_names[name_key] = service.pk
        service.code = normalized_code
        service.name = normalized_name

    Department.objects.bulk_update(departments, ('code', 'name', 'description'))
    Service.objects.bulk_update(services, ('code', 'name'))


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_service_is_discountable'),
    ]

    operations = [
        migrations.RunPython(normalize_catalog, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='unique_department_code_ci'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_department_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='unique_service_code_ci'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('department'), name='unique_service_name_per_department_ci'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(('standard_fee__gte', 0)), name='service_fee_nonnegative'),
        ),
    ]
