# Generated by Django 6.1.1 on 2026-09-23 06:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_department_unique_department_code_ci_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFeeHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('new_fee', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('reason', models.CharField(max_length=255)),
                ('changed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_fee_changes', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_history', to='departments.service')),
            ],
            options={
                'ordering': ('-changed_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(('new_fee__gte', 0)), name='service_fee_history_nonnegative')],
            },
        ),
    ]
