# Generated by Django 6.1.1 on 2026-09-22 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_deactivated_at_patient_deactivated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patientnote',
            name='amended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='amended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='amended_patient_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='note_type',
            field=models.CharField(choices=[('general', 'General'), ('clinical', 'Clinical'), ('allergy', 'Allergy'), ('administrative', 'Administrative')], default='general', max_length=20),
        ),
    ]
